# Generated by Django 4.1.5 on 2023-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriic', '0003_category_remove_item_category_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.TextField(blank=True, max_length=750, null=True),
        ),
    ]
